// 구매 가능 품목 카탈로그
// 경매 시세(data.go.kr) 기반 출하량이 높은 품목 = 안정적 구매 가능
// 소비자용 사진, 설명, 가용성 정보 포함

import type { AuctionItem } from './types';

/** 구매 가능 품목 */
export interface CatalogItem {
    id: string;
    name: string;               // 소비자용 이름
    itemName: string;           // 경매 품목명
    varietyName: string;        // 품종명
    categoryId: string;         // 카테고리 ID
    image: string;              // 이미지 경로 또는 이모지
    description: string;        // 소비자용 1줄 설명
    detailDescription: string;  // 상세 설명
    grade: string;              // 경매 등급
    avgPrice: number;           // 평균 경매 단가
    unitSize: number;           // 1박스 수량
    unit: string;               // 단위 (본, 분, 대)
    availability: 'high' | 'medium' | 'low'; // 출하량 기반 구매 가능성
    totalQuantity: number;      // 일일 총 출하량 (높을수록 구하기 쉬움)
    season: string;             // 제철/출하 시기
    care: string;               // 관리 팁 (소비자용)
    tags: string[];             // 태그 (선물용, 인테리어 등)
}

/** 경매 출하량 기반 구매 가능 품목 카탈로그 */
export const CATALOG_ITEMS: CatalogItem[] = [
    // ── 🌹 절화 (Cut Flowers) ──
    {
        id: 'item-001',
        name: '장미 레드나오미',
        itemName: '장미',
        varietyName: '레드나오미',
        categoryId: 'cat-cut',
        image: '/images/catalog/rose-red.jpg',
        description: '선명한 붉은색의 대표 장미. 꽃다발, 이벤트에 최적',
        detailDescription: '레드나오미는 국내 경매장에서 가장 많이 거래되는 장미 품종입니다. 60cm 이상의 긴 줄기와 진한 적색 꽃잎이 특징이며, 꽃다발이나 기념일 선물로 가장 인기 있는 품종입니다. 수명은 적절한 관리 시 7~10일입니다.',
        grade: '상',
        avgPrice: 950,
        unitSize: 20,
        unit: '본',
        availability: 'high',
        totalQuantity: 5000,
        season: '연중 출하 (봄·가을 최성수기)',
        care: '줄기 끝을 사선으로 잘라 깨끗한 물에 꽂아주세요. 직사광선을 피하고 2일마다 물을 교체해주세요.',
        tags: ['인기', '꽃다발', '선물', '이벤트'],
    },
    {
        id: 'item-002',
        name: '장미 샤넬',
        itemName: '장미',
        varietyName: '샤넬',
        categoryId: 'cat-cut',
        image: '/images/catalog/rose-chanel.jpg',
        description: '연분홍 고급 장미. 웨딩 부케, 프리미엄 선물에 인기',
        detailDescription: '샤넬 장미는 연한 분홍빛의 프리미엄 장미입니다. 고급스러운 색감으로 웨딩 부케, 기업 행사, 특별한 날의 선물로 많이 사용됩니다. 꽃잎이 겹겹이 풍성하여 볼륨감이 뛰어납니다.',
        grade: '상',
        avgPrice: 1250,
        unitSize: 20,
        unit: '본',
        availability: 'high',
        totalQuantity: 3000,
        season: '연중 출하',
        care: '서늘한 실내(15~20°C)에서 관리하면 오래 갑니다.',
        tags: ['프리미엄', '웨딩', '부케'],
    },
    {
        id: 'item-003',
        name: '장미 핑크오하라',
        itemName: '장미',
        varietyName: '핑크오하라',
        categoryId: 'cat-cut',
        image: '/images/catalog/rose-pink.jpg',
        description: '풍성한 꽃잎의 더블 핑크 장미. 빈티지 분위기',
        detailDescription: '핑크오하라는 오래된 영국 장미를 연상시키는 풍성한 겹꽃잎이 매력적인 품종입니다. 은은한 향기와 빈티지한 분위기로 카페, 화병 장식, SNS 인증샷용으로 인기가 많습니다.',
        grade: '중',
        avgPrice: 750,
        unitSize: 20,
        unit: '본',
        availability: 'high',
        totalQuantity: 4000,
        season: '봄·가을 (3~5월, 9~11월)',
        care: '꽃봉오리가 단단한 상태로 받으면 따뜻한 실내에서 1~2일 내 활짝 핍니다.',
        tags: ['빈티지', '인테리어', 'SNS'],
    },
    {
        id: 'item-004',
        name: '국화 백마',
        itemName: '국화',
        varietyName: '백마',
        categoryId: 'cat-cut',
        image: '/images/catalog/chrysanthemum.jpg',
        description: '순백의 대형 국화. 경조사, 화환, 제례용으로 필수',
        detailDescription: '백마 국화는 순백색의 대형 겹꽃으로, 경조사 화환과 제례용으로 가장 많이 사용되는 품종입니다. 출하량이 매우 많아 안정적으로 구매 가능하며, 꽃이 크고 수명이 길어 가성비가 뛰어납니다.',
        grade: '상',
        avgPrice: 650,
        unitSize: 10,
        unit: '본',
        availability: 'high',
        totalQuantity: 8000,
        season: '연중 출하 (가을 최대)',
        care: '줄기 아래 잎을 제거하고 깨끗한 물에 꽂으면 10일 이상 유지됩니다.',
        tags: ['경조사', '화환', '대량'],
    },
    {
        id: 'item-005',
        name: '백합 소르본',
        itemName: '백합',
        varietyName: '소르본',
        categoryId: 'cat-cut',
        image: '/images/catalog/lily.jpg',
        description: '향기로운 핑크빛 백합. 공간을 채우는 우아한 향',
        detailDescription: '소르본 백합은 연분홍빛 꽃잎과 진한 향기가 특징인 오리엔탈 백합입니다. 한 줄기에 3~5송이가 달려 풍성하며, 거실이나 사무실에 한 다발만 꽂아도 은은한 향기가 공간 전체를 채웁니다.',
        grade: '특',
        avgPrice: 3000,
        unitSize: 10,
        unit: '본',
        availability: 'high',
        totalQuantity: 2000,
        season: '연중 출하 (여름 피크)',
        care: '꽃가루가 옷에 묻으면 안 빠지니 수술을 미리 제거해주세요.',
        tags: ['향기', '프리미엄', '인테리어'],
    },
    {
        id: 'item-006',
        name: '카네이션 마스터',
        itemName: '카네이션',
        varietyName: '마스터',
        categoryId: 'cat-cut',
        image: '/images/catalog/carnation.jpg',
        description: '진한 빨강 카네이션. 어버이날·스승의날 필수',
        detailDescription: '마스터 카네이션은 선명한 적색의 스탠다드 카네이션입니다. 어버이날, 스승의날 시즌에 수요가 폭증하지만 출하량도 충분하여 안정적으로 구매할 수 있습니다. 수명이 길어 2주 이상 감상 가능합니다.',
        grade: '상',
        avgPrice: 500,
        unitSize: 25,
        unit: '본',
        availability: 'high',
        totalQuantity: 10000,
        season: '연중 (5월 피크)',
        care: '절화 수명이 매우 길어요. 시든 잎만 제거하면 2주 이상 유지됩니다.',
        tags: ['어버이날', '대량', '가성비'],
    },
    {
        id: 'item-007',
        name: '튤립 스트롱골드',
        itemName: '튤립',
        varietyName: '스트롱골드',
        categoryId: 'cat-cut',
        image: '/images/catalog/tulip.jpg',
        description: '선명한 노란 튤립. 봄의 상징, 밝은 분위기 연출',
        detailDescription: '스트롱골드는 생동감 넘치는 노란색 튤립으로, 봄 시즌 대표 절화입니다. 따뜻한 실내에서 빠르게 개화하며, 줄기가 계속 자라는 독특한 특성이 있어 매일 변하는 모습을 즐길 수 있습니다.',
        grade: '상',
        avgPrice: 1500,
        unitSize: 20,
        unit: '본',
        availability: 'medium',
        totalQuantity: 3000,
        season: '1~4월 (봄 한정)',
        care: '따뜻한 곳에 두면 빨리 피고, 시원한 곳에 두면 오래 감상하실 수 있어요.',
        tags: ['봄', '시즌', '인테리어'],
    },
    {
        id: 'item-008',
        name: '안개꽃 밀리언스타',
        itemName: '안개꽃',
        varietyName: '밀리언스타',
        categoryId: 'cat-cut',
        image: '/images/catalog/babysbreath.jpg',
        description: '하늘하늘한 순백 안개꽃. 꽃다발 필수 소재',
        detailDescription: '밀리언스타는 순백색의 작은 꽃이 구름처럼 피는 안개꽃입니다. 단독으로 드라이플라워로 만들어도 예쁘고, 다른 꽃과 함께 꽂으면 볼륨과 분위기를 살려줍니다. 드라이플라워로도 인기 만점입니다.',
        grade: '상',
        avgPrice: 400,
        unitSize: 10,
        unit: '단',
        availability: 'high',
        totalQuantity: 6000,
        season: '연중 출하',
        care: '거꾸로 매달아 건조하면 드라이플라워로 6개월 이상 감상 가능해요.',
        tags: ['드라이플라워', '꽃다발', '가성비'],
    },

    // ── 🪴 분화 (Potted Plants) ──
    {
        id: 'item-009',
        name: '호접란 아마빌리스',
        itemName: '호접란',
        varietyName: '아마빌리스',
        categoryId: 'cat-potted',
        image: '/images/catalog/phalaenopsis.jpg',
        description: '순백 호접란. 개업 축하, 명절 선물의 대명사',
        detailDescription: '아마빌리스는 순백색 호접란의 가장 대중적인 품종입니다. 개업 축하, 명절 선물, 어버이날 등 경조사에 빠지지 않는 선물용 화분입니다. 적절한 관리 시 2~3개월간 꽃을 감상할 수 있습니다.',
        grade: '특',
        avgPrice: 12000,
        unitSize: 6,
        unit: '대',
        availability: 'high',
        totalQuantity: 500,
        season: '연중 출하',
        care: '일주일에 한 번 물을 주고, 밝은 간접광에서 관리해주세요. 꽃이 지면 줄기를 2마디 남기고 잘라주세요.',
        tags: ['선물', '경조사', '개업'],
    },
    {
        id: 'item-010',
        name: '시클라멘 스카렛',
        itemName: '시클라멘',
        varietyName: '스카렛',
        categoryId: 'cat-potted',
        image: '/images/catalog/cyclamen.jpg',
        description: '겨울 화분의 여왕. 선명한 빨강으로 실내를 화사하게',
        detailDescription: '스카렛 시클라멘은 겨울 시즌 대표 분화식물입니다. 선명한 빨강색 꽃이 잎 위로 우아하게 피어오르며, 서늘한 환경에서 3~4개월간 계속 꽃을 피웁니다. 크리스마스, 연말 선물로 인기가 많습니다.',
        grade: '상',
        avgPrice: 6500,
        unitSize: 8,
        unit: '분',
        availability: 'medium',
        totalQuantity: 1000,
        season: '10월~2월 (겨울)',
        care: '서늘한 곳(10~15°C)을 좋아합니다. 물은 화분 받침에 부어주세요 (저면관수).',
        tags: ['겨울', '크리스마스', '화분'],
    },

    // ── 🌿 관엽 (Foliage) ──
    {
        id: 'item-011',
        name: '몬스테라 델리시오사',
        itemName: '몬스테라',
        varietyName: '델리시오사',
        categoryId: 'cat-foliage',
        image: '/images/catalog/monstera.jpg',
        description: '대형 갈라진 잎이 매력적. 인테리어 식물 1위',
        detailDescription: '몬스테라 델리시오사는 큰 잎에 독특한 구멍이 있는 열대 관엽식물로, 인테리어 트렌드를 이끄는 인기 식물입니다. 공기 정화 효과도 우수하며, 빠른 생장 속도로 키우는 재미가 있습니다.',
        grade: '상',
        avgPrice: 15000,
        unitSize: 4,
        unit: '분',
        availability: 'medium',
        totalQuantity: 300,
        season: '연중 출하',
        care: '밝은 간접광, 주 1회 물주기. 잎에 먼지가 쌓이면 젖은 천으로 닦아주세요.',
        tags: ['인테리어', '공기정화', '트렌디'],
    },
    {
        id: 'item-012',
        name: '스투키 실린드리카',
        itemName: '스투키',
        varietyName: '실린드리카',
        categoryId: 'cat-foliage',
        image: '/images/catalog/stuckyi.jpg',
        description: '둥근 막대 형태의 공기정화 식물. 관리 초간단',
        detailDescription: '스투키는 산세베리아의 일종으로, 원통형 잎이 위로 곧게 자라는 모던한 식물입니다. NASA 선정 공기정화 식물 중 하나이며, 물을 한 달에 한 번만 줘도 잘 자라 초보자도 쉽게 키울 수 있습니다.',
        grade: '상',
        avgPrice: 4500,
        unitSize: 10,
        unit: '분',
        availability: 'high',
        totalQuantity: 800,
        season: '연중 출하',
        care: '물은 한 달에 한 번, 과습 주의! 그 외에는 거의 신경 쓰지 않아도 됩니다.',
        tags: ['공기정화', '초보추천', '모던'],
    },
];

/** 가용성 라벨 */
export const AVAILABILITY_LABEL: Record<string, { label: string; color: string; emoji: string }> = {
    high: { label: '구매 쉬움', color: 'text-green-600', emoji: '🟢' },
    medium: { label: '시즌 한정', color: 'text-amber-600', emoji: '🟡' },
    low: { label: '희소', color: 'text-red-500', emoji: '🔴' },
};
